# Generated by Django 4.2.5 on 2023-11-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctolib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalformrecord',
            name='quantite_eau_litre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
