# Generated by Django 4.2.5 on 2023-11-15 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_medecinpatient_idmedecin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecinpatient',
            name='idMedecin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medecinPatient', to=settings.AUTH_USER_MODEL),
        ),
    ]
