# Generated by Django 4.2.5 on 2023-11-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_alter_medecinpatient_idmedecin'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='period_general_from',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='period_stress_from',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
